#!/system/bin/sh
MODDIR="${0%/*}"
[[ ! -d $MODDIR/tools ]] && echo "$MODDIR/tools目錄遺失" && exit 1
tools_path="$MODDIR/tools"
txt="$MODDIR/應用列表.txt"
. "$tools_path/bin.sh"
echo "#不需要恢復還原的應用請在開頭注釋# 比如#xxxxxxxx 酷安">"$txt"
find "$MODDIR" -maxdepth 1 -type d | sort | sed 's/(/ /g ; s/)//g' | while read; do
	case ${REPLY##*/} in
	媒體|tools|Backup_*) ;;
	*) echo "${REPLY##*/}">>"$txt" ;;
	esac
done
echoRgb "$txt重新生成"