#!/system/bin/sh
MODDIR="${0%/*}"
bin_path="$MODDIR/tools/bin"
[[ ! -d $bin_path ]] && echo "$bin_path目錄遺失" && exit 1
txt="$MODDIR/應用列表.txt"
. "$bin_path/bin.sh"
echo "#不需要恢復還原的應用請在開頭注釋# 比如#xxxxxxxx 酷安">"$txt"
find "$MODDIR" -maxdepth 1 -type d | sort | sed 's/\[/ /g ; s/\]//g' | while read; do
	if [[ -f $REPLY/app_details ]]; then
		unset PackageName
		. $REPLY/app_details
		if [[ $PackageName != "" ]]; then
			echo "${REPLY##*/} $PackageName">>"$txt"
		fi
	fi
done
echoRgb "$txt重新生成"