#!/system/bin/sh
# SpeedBackup entry wrapper generated by tools.sh.
# 446: resolve physical script directory first; relative invocations like ./recover.sh must not turn into ./recover.sh/tools/tools.sh.
_sb_entry_file="$0"
case "$_sb_entry_file" in
	*/*) ;;
	*)
		_sb_cmd="$(command -v "$_sb_entry_file" 2>/dev/null)"
		[ -n "$_sb_cmd" ] && _sb_entry_file="$_sb_cmd"
		;;
esac
_sb_entry_dir="${_sb_entry_file%/*}"
[ "$_sb_entry_dir" = "$_sb_entry_file" ] && _sb_entry_dir="."
_sb_entry_dir="$(cd "$_sb_entry_dir" 2>/dev/null && pwd -P)"
if [ -z "$_sb_entry_dir" ]; then
	echo "SpeedBackup 入口錯誤: 無法解析腳本目錄: $0"
	exit 127
fi
_sb_abs_dir() {
	(cd "$1" 2>/dev/null && pwd -P) || return 1
}
_sb_root="$(_sb_abs_dir "$_sb_entry_dir/.")" || _sb_root=""
_sb_moddir="$(_sb_abs_dir "$_sb_entry_dir/.")" || _sb_moddir=""
conf_path="$_sb_entry_dir/backup_settings.conf"
case "$conf_path" in
	/*) ;;
	*) conf_path="$(_sb_abs_dir "${conf_path%/*}" 2>/dev/null)/${conf_path##*/}" ;;
esac
if [ -z "$_sb_root" ] || [ -z "$_sb_moddir" ]; then
	echo "SpeedBackup 入口錯誤: 無法解析根目錄 root=$_sb_root moddir=$_sb_moddir script=$0"
	exit 127
fi
if [ ! -f "$_sb_root/tools/tools.sh" ]; then
	echo "$_sb_root/tools/tools.sh遺失"
	exit 127
fi
MODDIR="$_sb_moddir"
# 入口腳本自己的 log 目錄必須自行建立；不能引用 tools.sh 上一次 run 的 speed_debug 路徑。
# r366: 全新解壓時 log/ 不存在也不得讓入口報錯；主路徑失敗才退到 /data/local/tmp/speedbackup_log。
_log_dir="$_sb_entry_dir/log"
if ! mkdir -p "$_log_dir" 2>/dev/null; then
	_log_dir="/data/local/tmp/speedbackup_log"
	mkdir -p "$_log_dir" 2>/dev/null || _log_dir="/data/local/tmp"
fi
logfile="$_log_dir/log_$(date +%Y-%m-%d_%H-%M).txt"
: > "$logfile" 2>/dev/null || logfile="/dev/null"
# 由入口腳本啟動時，trap 收尾訊息只寫 speed_debug，不刷終端，避免單獨恢復開頭出現 trap 訊息。
export SPEEDBACKUP_ENTRY_QUIET_TRAP=1
export SPEEDBACKUP_ENTRY_MODE="0"
export SPEEDBACKUP_ENTRY_SCRIPT="$0"
# 防止舊入口腳本 / 父 shell 殘留上一輪 speed_debug run_xxx 變數，導致單獨腳本誤寫已被 final 刪除的 main.log/stderr.log。
unset SPEED_DEBUG_RUN_DIR SPEED_DEBUG_MAIN_LOG SPEED_DEBUG_PENDING_ERR_LOG SPEED_DEBUG_CMD_LOG SPEED_DEBUG_INFO_LOG SPEED_DEBUG_DEX_HUMAN_LOG SPEED_DEBUG_ARCHIVE SPEED_DEBUG_PACKED SPEED_DEBUG_SNAPSHOT_DONE SPEED_DEBUG_RUN_DIR_REMOVED SPEED_DEBUG_ERR_LOG
# 446: 不可使用 `. tools.sh | tee`。source 放在 pipeline 內會讓部分 shell/入口條件下主流程直接退出或在 subshell 中跑壞。
# r36: legacy logfile 由 _speed_debug_sync_legacy_log 在 final/snapshot 打包前寫入 main.log 鏡像；實際診斷仍以 /data/speed_debug 內 speed_debug 包為準。
. "$_sb_root/tools/tools.sh"
_entry_rc=$?
case "$_entry_rc" in
	''|*[!0-9]*) _entry_rc=1 ;;
esac
if [ "$logfile" != "/dev/null" ] && [ -f "$logfile" ]; then
	sed -i "$(printf 's/\033\[[0-9;]*m//g')" "$logfile" 2>/dev/null || true
fi
exit "$_entry_rc"
