[package]
name = "speedbackup-native-rs"
version = "0.1.705"
edition = "2021"
autobins = false
license = "MIT"

# No third-party crates. Android builds do not need network access.
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[[bin]]
name = "speednative"
path = "src/main.rs"
